/**
 * KEYWORD_ALIASES
 * ─────────────────────────────────────────────────────────────────────────
 * Keyword → category-name aliases used to match free-text input (chat notes,
 * user prompts) against real category names fetched from the DB.
 *
 * DESIGN NOTES (why this file looks the way it does):
 *
 * 1. SPELLING VARIANCE IS THE #1 CAUSE OF "Other" MISCLASSIFICATION.
 *    Indian food/place/brand names get transliterated inconsistently
 *    (biryani / biriyani / briyani / behrani), so every high-frequency word
 *    is listed with its common spelling variants as separate keys pointing
 *    to the same alias list. Don't dedupe these away — each spelling needs
 *    its own regex match.
 *
 * 2. Keys are lowercase, matched with a \b word-boundary regex, so multi-word
 *    dish/place names are still single keys (e.g. "pav bhaji") — the calling
 *    code should build the regex the same way for phrases (replace spaces
 *    with \s+ if needed).
 *
 * 3. Values are ordered by priority — the first alias that exists as a real
 *    category in the user's DB wins. Keep the most specific category first
 *    (e.g. "Groceries" before "Food" for grocery-specific words).
 *
 * 4. Brand/app names (Swiggy, Ola, Jio, etc.) are extremely high-signal in
 *    Indian expense text and should always be included — people say "paid
 *    swiggy 350" far more often than "paid for food 350".
 */

export const KEYWORD_ALIASES: Record<string, string[]> = {

  // ── Transport / Travel ────────────────────────────────────────────────
  taxi: ["Travel", "Transport"],
  cab: ["Travel", "Transport"],
  uber: ["Travel", "Transport"],
  ola: ["Travel", "Transport"],
  olacabs: ["Travel", "Transport"],
  rapido: ["Transport", "Travel"],
  "namma yatri": ["Transport", "Travel"],
  auto: ["Transport", "Travel"],
  autorickshaw: ["Transport", "Travel"],
  "auto rickshaw": ["Transport", "Travel"],
  rickshaw: ["Transport", "Travel"],
  "shared auto": ["Transport", "Travel"],
  bus: ["Transport", "Travel"],
  "state bus": ["Transport", "Travel"],
  ksrtc: ["Transport", "Travel"],
  msrtc: ["Transport", "Travel"],
  tsrtc: ["Transport", "Travel"],
  volvo: ["Transport", "Travel"],
  redbus: ["Transport", "Travel"],
  train: ["Transport", "Travel"],
  irctc: ["Transport", "Travel"],
  railway: ["Transport", "Travel"],
  "railway ticket": ["Transport", "Travel"],
  sleeper: ["Transport", "Travel"],
  tatkal: ["Transport", "Travel"],
  metro: ["Transport", "Travel"],
  "metro card": ["Transport", "Travel"],
  "metro recharge": ["Transport", "Travel"],
  local: ["Transport", "Travel"],
  "local train": ["Transport", "Travel"],
  flight: ["Travel", "Transport"],
  flightticket: ["Travel", "Transport"],
  "flight ticket": ["Travel", "Transport"],
  airline: ["Travel", "Transport"],
  airfare: ["Travel", "Transport"],
  indigo: ["Travel", "Transport"],
  spicejet: ["Travel", "Transport"],
  vistara: ["Travel", "Transport"],
  "air india": ["Travel", "Transport"],
  akasa: ["Travel", "Transport"],
  boardingpass: ["Travel", "Transport"],
  hotel: ["Travel"],
  oyo: ["Travel"],
  airbnb: ["Travel"],
  lodge: ["Travel"],
  homestay: ["Travel"],
  trip: ["Travel"],
  vacation: ["Travel"],
  holiday: ["Travel"],
  tour: ["Travel"],
  makemytrip: ["Travel"],
  goibibo: ["Travel"],
  yatra: ["Travel"],
  cleartrip: ["Travel"],
  ixigo: ["Travel", "Transport"],
  petrol: ["Fuel", "Transport"],
  diesel: ["Fuel", "Transport"],
  cng: ["Fuel", "Transport"],
  fuel: ["Fuel", "Transport"],
  "petrol pump": ["Fuel", "Transport"],
  "ev charging": ["Fuel", "Transport"],
  toll: ["Transport", "Travel"],
  fastag: ["Transport", "Travel"],
  parking: ["Transport"],
  "vehicle service": ["Transport"],
  "bike service": ["Transport"],
  "car service": ["Transport"],
  puncture: ["Transport"],

  // ── Food ─────────────────────────────────────────────────────────────
  groceries: ["Groceries", "Food"],
  grocery: ["Groceries", "Food"],
  kirana: ["Groceries", "Food"],
  bigbasket: ["Groceries", "Food"],
  blinkit: ["Groceries", "Food"],
  zepto: ["Groceries", "Food"],
  instamart: ["Groceries", "Food"],
  dunzo: ["Groceries", "Food"],
  dmart: ["Groceries", "Food"],
  "reliance fresh": ["Groceries", "Food"],
  "more supermarket": ["Groceries", "Food"],
  spencers: ["Groceries", "Food"],
  "nature basket": ["Groceries", "Food"],
  vegetables: ["Groceries", "Food"],
  veggies: ["Groceries", "Food"],
  fruits: ["Groceries", "Food"],
  milk: ["Groceries", "Food"],
  eggs: ["Groceries", "Food"],
  dinner: ["Food"],
  lunch: ["Food"],
  breakfast: ["Food"],
  snack: ["Food"],
  snacks: ["Food"],
  tiffin: ["Food"],
  meals: ["Food"],
  thali: ["Food"],
  mess: ["Food"],
  canteen: ["Food"],
  cafeteria: ["Food"],
  coffee: ["Food"],
  ccd: ["Food"],
  "cafe coffee day": ["Food"],
  starbucks: ["Food"],
  chai: ["Food"],
  tea: ["Food"],
  juice: ["Food"],
  lassi: ["Food"],
  milkshake: ["Food"],
  restaurant: ["Food"],
  hotel_food: ["Food"], // placeholder key, avoid clash with Travel "hotel"
  dhaba: ["Food"],
  swiggy: ["Food"],
  zomato: ["Food"],
  eatsure: ["Food"],
  faasos: ["Food"],
  // — Indian dish / cuisine names (with common spelling variants) —
  biryani: ["Food"],
  biriyani: ["Food"],
  briyani: ["Food"],
  behrani: ["Food"],
  pulao: ["Food"],
  "fried rice": ["Food"],
  friedrice: ["Food"],
  noodles: ["Food"],
  chowmein: ["Food"],
  "chow mein": ["Food"],
  momos: ["Food"],
  momo: ["Food"],
  idli: ["Food"],
  idly: ["Food"],
  dosa: ["Food"],
  dosai: ["Food"],
  vada: ["Food"],
  vadai: ["Food"],
  sambar: ["Food"],
  sambhar: ["Food"],
  chutney: ["Food"],
  uttapam: ["Food"],
  uthappam: ["Food"],
  poha: ["Food"],
  upma: ["Food"],
  paratha: ["Food"],
  parota: ["Food"],
  parotta: ["Food"],
  porotta: ["Food"],
  roti: ["Food"],
  chapati: ["Food"],
  chapathi: ["Food"],
  naan: ["Food"],
  kulcha: ["Food"],
  sabzi: ["Food"],
  sabji: ["Food"],
  curry: ["Food"],
  dal: ["Food"],
  daal: ["Food"],
  rajma: ["Food"],
  chole: ["Food"],
  cholebhature: ["Food"],
  "chole bhature": ["Food"],
  paneer: ["Food"],
  samosa: ["Food"],
  samosas: ["Food"],
  kachori: ["Food"],
  pakora: ["Food"],
  pakoda: ["Food"],
  bhaji: ["Food"],
  bajji: ["Food"],
  "vada pav": ["Food"],
  vadapav: ["Food"],
  "pav bhaji": ["Food"],
  pavbhaji: ["Food"],
  dabeli: ["Food"],
  chaat: ["Food"],
  chat: ["Food"],
  "bhel puri": ["Food"],
  bhelpuri: ["Food"],
  "sev puri": ["Food"],
  sevpuri: ["Food"],
  "pani puri": ["Food"],
  panipuri: ["Food"],
  golgappa: ["Food"],
  golgappe: ["Food"],
  gupchup: ["Food"],
  "dahi puri": ["Food"],
  tikki: ["Food"],
  "curd rice": ["Food"],
  curdrice: ["Food"],
  "lemon rice": ["Food"],
  "puliyodarai": ["Food"],
  chicken: ["Food"],
  mutton: ["Food"],
  fish: ["Food"],
  "fish curry": ["Food"],
  "egg curry": ["Food"],
  omelette: ["Food"],
  omelet: ["Food"],
  sandwich: ["Food"],
  burger: ["Food"],
  pizza: ["Food"],
  dominos: ["Food"],
  mcdonalds: ["Food"],
  kfc: ["Food"],
  subway: ["Food"],
  bakery: ["Food"],
  bread: ["Food"],
  cake: ["Food"],
  sweets: ["Food"],
  mithai: ["Food"],
  "gulab jamun": ["Food"],
  gulabjamun: ["Food"],
  rasgulla: ["Food"],
  rasagulla: ["Food"],
  jalebi: ["Food"],
  laddu: ["Food"],
  ladoo: ["Food"],
  barfi: ["Food"],
  burfi: ["Food"],
  halwa: ["Food"],
  kheer: ["Food"],
  "ice cream": ["Food"],
  icecream: ["Food"],

  // ── Sports / Fitness ─────────────────────────────────────────────────
  badminton: ["Sports", "Fitness", "Entertainment"],
  badmitton: ["Sports", "Fitness", "Entertainment"],
  football: ["Sports", "Fitness"],
  cricket: ["Sports", "Fitness"],
  "gully cricket": ["Sports", "Fitness"],
  "box cricket": ["Sports", "Fitness"],
  kabaddi: ["Sports", "Fitness"],
  "kho kho": ["Sports", "Fitness"],
  khokho: ["Sports", "Fitness"],
  carrom: ["Sports", "Entertainment"],
  chess: ["Sports", "Entertainment"],
  "table tennis": ["Sports", "Fitness"],
  tabletennis: ["Sports", "Fitness"],
  tt: ["Sports", "Fitness"],
  volleyball: ["Sports", "Fitness"],
  hockey: ["Sports", "Fitness"],
  turf: ["Sports", "Fitness"],
  gym: ["Sports", "Fitness", "Health"],
  tennis: ["Sports", "Fitness"],
  basketball: ["Sports", "Fitness"],
  swimming: ["Sports", "Fitness", "Health"],
  yoga: ["Sports", "Fitness", "Health"],
  zumba: ["Sports", "Fitness", "Health"],
  crossfit: ["Sports", "Fitness", "Health"],
  aerobics: ["Sports", "Fitness", "Health"],
  squash: ["Sports", "Fitness"],
  marathon: ["Sports", "Fitness"],
  running: ["Sports", "Fitness"],
  cycling: ["Sports", "Fitness"],
  cycle: ["Sports", "Fitness"],
  "sports club": ["Sports", "Fitness"],
  stadium: ["Sports", "Fitness"],
  "personal trainer": ["Fitness", "Sports", "Health"],
  "pt session": ["Fitness", "Sports", "Health"],

  // ── Health ───────────────────────────────────────────────────────────
  medicine: ["Health", "Medical"],
  medicines: ["Health", "Medical"],
  tablets: ["Health", "Medical"],
  doctor: ["Health", "Medical"],
  hospital: ["Health", "Medical"],
  pharmacy: ["Health", "Medical"],
  apollo: ["Health", "Medical"],
  practo: ["Health", "Medical"],
  "1mg": ["Health", "Medical"],
  pharmeasy: ["Health", "Medical"],
  netmeds: ["Health", "Medical"],
  clinic: ["Health", "Medical"],
  dentist: ["Health", "Medical"],
  checkup: ["Health", "Medical"],
  "blood test": ["Health", "Medical"],
  scan: ["Health", "Medical"],
  xray: ["Health", "Medical"],
  physiotherapy: ["Health", "Medical"],
  ambulance: ["Health", "Medical"],
  "health insurance": ["Health", "Medical"],
  consultation: ["Health", "Medical"],

  // ── Entertainment ────────────────────────────────────────────────────
  cinema: ["Entertainment"],
  movie: ["Entertainment"],
  movies: ["Entertainment"],
  bookmyshow: ["Entertainment"],
  pvr: ["Entertainment"],
  inox: ["Entertainment"],
  cinepolis: ["Entertainment"],
  netflix: ["Entertainment", "Subscription"],
  spotify: ["Entertainment", "Subscription"],
  "amazon prime": ["Entertainment", "Subscription"],
  primevideo: ["Entertainment", "Subscription"],
  hotstar: ["Entertainment", "Subscription"],
  jiocinema: ["Entertainment", "Subscription"],
  sonyliv: ["Entertainment", "Subscription"],
  zee5: ["Entertainment", "Subscription"],
  gaana: ["Entertainment", "Subscription"],
  wynk: ["Entertainment", "Subscription"],
  concert: ["Entertainment"],
  gaming: ["Entertainment"],
  pubg: ["Entertainment"],
  playstation: ["Entertainment"],
  xbox: ["Entertainment"],
  steam: ["Entertainment"],
  "amusement park": ["Entertainment"],
  waterpark: ["Entertainment"],
  "water park": ["Entertainment"],
  zoo: ["Entertainment"],
  museum: ["Entertainment"],
  picnic: ["Entertainment"],
  outing: ["Entertainment"],

  // ── Shopping ─────────────────────────────────────────────────────────
  shoes: ["Shopping"],
  clothes: ["Shopping"],
  clothing: ["Shopping"],
  puma: ["Shopping"],
  adidas: ["Shopping"],
  nike: ["Shopping"],
  reebok: ["Shopping"],
  bata: ["Shopping"],
  amazon: ["Shopping"],
  flipkart: ["Shopping"],
  myntra: ["Shopping"],
  ajio: ["Shopping"],
  nykaa: ["Shopping"],
  meesho: ["Shopping"],
  snapdeal: ["Shopping"],
  tatacliq: ["Shopping"],
  croma: ["Shopping"],
  "reliance digital": ["Shopping"],
  "big bazaar": ["Shopping"],
  lifestyle: ["Shopping"],
  pantaloons: ["Shopping"],
  westside: ["Shopping"],
  "max fashion": ["Shopping"],
  "shoppers stop": ["Shopping"],
  decathlon: ["Shopping", "Sports"],
  electronics: ["Shopping"],
  mobile: ["Shopping"],
  laptop: ["Shopping"],
  cosmetics: ["Shopping"],
  makeup: ["Shopping"],
  jewellery: ["Shopping"],
  jewelry: ["Shopping"],
  watch: ["Shopping"],
  bag: ["Shopping"],
  wallet: ["Shopping"],

  // ── Education ────────────────────────────────────────────────────────
  course: ["Education"],
  book: ["Education"],
  books: ["Education"],
  school: ["Education"],
  college: ["Education"],
  tuition: ["Education"],
  coaching: ["Education"],
  fees: ["Education"],
  "exam fee": ["Education"],
  admission: ["Education"],
  byjus: ["Education"],
  unacademy: ["Education"],
  udemy: ["Education"],
  coursera: ["Education"],
  stationery: ["Education"],
  uniform: ["Education"],
  notebooks: ["Education"],

  // ── Bills & Utilities ────────────────────────────────────────────────
  electricity: ["Utilities", "Bills"],
  eb: ["Utilities", "Bills"],
  water: ["Utilities", "Bills"],
  internet: ["Utilities", "Bills"],
  broadband: ["Utilities", "Bills"],
  wifi: ["Utilities", "Bills"],
  phone: ["Bills", "Utilities"],
  recharge: ["Bills", "Utilities"],
  jio: ["Bills", "Utilities"],
  airtel: ["Bills", "Utilities"],
  vi: ["Bills", "Utilities"],
  vodafone: ["Bills", "Utilities"],
  bsnl: ["Bills", "Utilities"],
  dth: ["Bills", "Utilities"],
  tatasky: ["Bills", "Utilities"],
  "gas cylinder": ["Bills", "Utilities"],
  lpg: ["Bills", "Utilities"],
  maintenance: ["Bills", "Utilities"],
  "society maintenance": ["Bills", "Utilities"],

  // ── Rent ─────────────────────────────────────────────────────────────
  rent: ["Rent"],
  "house rent": ["Rent"],
  "pg rent": ["Rent"],
  "hostel fee": ["Rent"],
  deposit: ["Rent"],
  brokerage: ["Rent"],
};


/**
 * SPORTS_KEYWORDS
 * ─────────────────────────────────────────────────────────────────────────
 * Flat list of sports/fitness-related words used for history-pattern
 * detection (e.g. "you've logged sports expenses before, want to create a
 * Sports category?"). Kept separate from KEYWORD_ALIASES because this list
 * is used for:
 *   1. A quick single-keyword extraction (extractSportsKeyword)
 *   2. A Prisma `OR: [{ note: { contains: kw } }, ...]` history lookup
 *
 * Includes popular Indian sports (kabaddi, kho-kho, gully cricket) alongside
 * global ones, plus common spelling variants people actually type.
 */

export const SPORTS_KEYWORDS: string[] = [
  // Bat & ball / field sports
  "cricket",
  "gully cricket",
  "box cricket",
  "football",
  "hockey",
  "volleyball",
  "basketball",
  "baseball",
  "kabaddi",
  "kho kho",
  "khokho",

  // Racquet & indoor sports
  "badminton",
  "badmitton",
  "tennis",
  "table tennis",
  "tabletennis",
  "tt",
  "squash",
  "carrom",
  "chess",

  // Fitness / gym / wellness
  "gym",
  "yoga",
  "zumba",
  "crossfit",
  "aerobics",
  "pilates",
  "personal trainer",
  "pt session",

  // Water & endurance sports
  "swimming",
  "marathon",
  "running",
  "cycling",
  "cycle",

  // Facilities / bookings
  "turf",
  "stadium",
  "sports club",
  "sports complex",
  "playzone",
  "arena",
];