export const TRAINING_DATA: Record<string, string[]> = {
  expense_summary: [
    "what's my spending this month?",
    "how much have i spent this week?",
    "show my spending for last month",
    "what's my total spending this year?",
    "how much did i spend yesterday?",
    "show all expenses from this month",
    "how much have i spent so far?",
    "total expenses",
    "my spending overview",
    "what did i spend today?", "show my expenses",
    "show all my expenses",
    "display my expenses",
    "how much have i spent",
    "how much money have i spent",
    "total spending",
    "total expenses for this month",
    "monthly expenses",
    "this month's expenses",
    "expense summary",
    "give me my expense summary",
    "show my monthly spending",
    "how much did i spend this month",
    "how much have i spent this month",
    "show spending for today",
    "today's expenses",
    "yesterday's expenses",
    "show expenses for yesterday",
    "show expenses for this week",
    "show expenses for last week",
    "show expenses for this year",
    "what are my expenses",
    "how much did i spend so far this month",
    "what's my total expenditure",
    "how much money went out this month",
    "show all spending",
    "expense report",
    "give me spending details",
    "show expense history",
    "what did i spend recently",
    "show recent expenses",
    "how much did i spend over the weekend",
    "show my spending this quarter",
    "display total expenses",
    "how much have i spent this year",
    "show expenses from june",
    "expenses for july",
    "money spent this month",
    "overall spending",
    "show financial outflow"
  ],

  income_summary: [
    "show my income this month",
    "how much income did i receive last month?",
    "show income history",
    "what's my total income this year?",
    "my earnings this month",
    "show all money earned this year",
    "show my earnings",
    "show salary",
    "display my income",
    "income summary",
    "monthly income",
    "how much did i earn this month",
    "earnings this month",
    "income report",
    "show all income",
    "show recent income",
    "income history",
    "display income history",
    "salary history",
    "money received this month",
    "cash received this month",
    "total earnings",
    "annual income",
    "yearly income",
    "income for june",
    "income for july",
    "income this week",
    "income today",
    "show my latest income",
    "how much money have i earned",
    "show incoming money",
    "what is my income so far",
    "show salary received",
    "how much income do i have",
    "income overview",
    "show all earnings"
  ],

  budget_status: [
    "show my budget",
    "what's my remaining budget?",
    "have i exceeded my budget?",
    "how much budget is left?",
    "show budget utilization",
    "which budget category is almost full?",
    "am i within my monthly budget?",
    "how much can i still spend?",
    "budget summary",
    "show budget details",
    "remaining budget",
    "budget left",
    "how much budget remains",
    "how much money can i spend",
    "available budget",
    "budget overview",
    "show current budget",
    "budget usage",
    "budget progress",
    "how much have i used",
    "show budget balance",
    "remaining spending limit",
    "did i exceed my budget",
    "am i over budget",
    "how close am i to my budget",
    "budget status",
    "show monthly budget",
    "how much budget is available",
    "how much budget is unused",
    "budget report",
    "budget breakdown",
    "show all budgets",
    "display budgets",
    "show category budgets",
    "which budget is exceeded",
    "which category is over budget",
    "how much is left in groceries budget",
    "how much is left in shopping budget"
  ],

  category_spending: [
    "how much did i spend on groceries this month?",
    "show my food expenses",
    "what's my transportation spending this month?",
    "how much have i spent on shopping?",
    "show entertainment expenses",
    "compare grocery spending with dining",
    "how much did i spend on bills last month?",
    "show expenses by category",
    "food spending",
    "grocery expenses",
    "food expenses",
    "dining expenses",
    "fuel expenses",
    "travel expenses",
    "shopping expenses",
    "medical expenses",
    "entertainment expenses",
    "education expenses",
    "utility expenses",
    "electricity expenses",
    "rent expenses",
    "internet expenses",
    "mobile recharge expenses",
    "how much did i spend on fuel",
    "how much did i spend on transport",
    "how much on food",
    "money spent on groceries",
    "money spent on shopping",
    "expenses for dining",
    "show spending by category",
    "category breakdown",
    "show category summary",
    "top spending category",
    "show grocery spending",
    "show travel spending",
    "show utility bills",
    "compare groceries and shopping",
    "compare food and transport",
    "show category wise expenses"
  ],

  spending_analysis: [
    "where am i spending the most money?",
    "what are my biggest expenses?",
    "what is my average daily spending?",
    "how much do i spend on weekends?",
    "what is my highest spending category?",
    "show my top categories",
    "analyze my spending",
    "analyze expenses",
    "where does my money go",
    "what do i spend most on",
    "biggest spending",
    "largest expense",
    "highest expense",
    "highest spending category",
    "which category costs me the most",
    "average spending",
    "average monthly spending",
    "average weekly spending",
    "daily average expense",
    "show expensive categories",
    "find my biggest expenses",
    "what are my largest purchases",
    "show expense analysis",
    "expense insights",
    "money usage analysis",
    "analyze my financial habits",
    "show expense statistics",
    "where am i overspending",
    "find unnecessary spending",
    "how am i spending my money",
    "expense distribution"
  ],
  trend_analysis: [
    "has my spending increased this month?",
    "which category increased the most?",
    "which category decreased the most?",
    "show my spending trends",
    "is my grocery spending increasing?",
    "how has my spending changed?",
    "expense trend",
    "monthly trend",
    "weekly trend",
    "yearly trend",
    "show expense graph",
    "show spending over time",
    "how is my spending changing",
    "is spending increasing",
    "is spending decreasing",
    "compare spending trend",
    "show growth in spending",
    "show decline in spending",
    "monthly expense trend",
    "expense history trend",
    "income trend",
    "budget trend",
    "show trend analysis",
    "expense comparison over time",
    "show last six months trend",
    "show yearly spending trend",
    "how has grocery spending changed",
    "how has shopping spending changed",
    "trend of dining expenses",
    "expense growth",
    "financial trend"
  ],

  comparison: [
    "compare this month's spending with last month",
    "compare grocery spending for june and july",
    "did i spend more on dining or shopping?",
    "compare income and expenses",
    "which month had the highest spending?",
    "compare today and yesterday",
    "compare this week and last week",
    "compare this month and last month",
    "compare june and july expenses",
    "compare grocery and fuel spending",
    "compare salary and expenses",
    "compare income this month and last month",
    "which month did i spend more",
    "which category spent the most",
    "compare shopping with entertainment",
    "compare dining with groceries",
    "expense comparison",
    "income vs expense",
    "budget vs spending",
    "compare spending across categories",
    "compare annual spending",
    "compare yearly income",
    "show comparison report",
    "month over month comparison",
    "weekly comparison"
  ],

  financial_insights: [
    "where can i save money?",
    "which expenses are unusually high?",
    "what are my top spending categories?",
    "what is my biggest recurring expense?",
    "summarize my finances",
    "give me an overview of this month's finances",
    "what are my spending habits?",
    "show financial insights",
    "give me insights",
    "show insights",
    "financial overview",
    "how am i managing my money",
    "where should i cut expenses",
    "where can i reduce spending",
    "give me spending advice",
    "show recommendations",
    "show saving opportunities",
    "how can i save more",
    "show unusual expenses",
    "show abnormal spending",
    "summarize my money",
    "summarize my spending",
    "summarize my income",
    "financial health",
    "money management summary",
    "show finance summary",
    "show spending patterns",
    "give me financial analysis",
    "expense recommendations",
    "budget recommendations",
    "show smart insights",
    "how healthy are my finances",
    "financial report"
  ],

  add_expense: [
    "add an expense of ₹250 for lunch today",
    "record ₹1200 for groceries",
    "add a fuel expense of ₹800",
    "i spent ₹650 on shopping yesterday",
    "record ₹1500 for electricity bill",
    "add coffee expense ₹180",
    "spent ₹900 on dinner",
    "i had lunch for ₹350 today",
    "bought groceries worth ₹1200",
    "add expense",
    "create expense",
    "new expense",
    "log expense",
    "save expense",
    "record an expense",
    "spent 500",
    "spent ₹500",
    "i spent 500",
    "paid ₹1200 for rent",
    "paid 200 for coffee",
    "bought vegetables for ₹350",
    "purchased groceries for ₹900",
    "movie tickets cost ₹600",
    "fuel cost ₹1000",
    "petrol ₹1500",
    "paid internet bill ₹900",
    "paid electricity ₹1800",
    "paid water bill ₹450",
    "cab fare ₹250",
    "bus ticket ₹80",
    "train ticket ₹650",
    "had dinner costing ₹700",
    "ordered food worth ₹500",
    "medical bill ₹2500",
    "doctor consultation ₹700",
    "pharmacy expense ₹450",
    "shopping ₹3500",
    "gift expense ₹1200",
    "office lunch ₹300"
  ],

  add_income: [
    "record salary income of ₹45000",
    "add freelance income of ₹15000",
    "record bonus income",
    "add rental income",
    "record ₹5000 as cash received",
    "salary credited today ₹55000",
    "add income",
    "record income",
    "new income",
    "salary received",
    "salary credited",
    "received salary",
    "got paid ₹50000",
    "received ₹5000",
    "bonus received",
    "freelance payment received",
    "client payment ₹25000",
    "cash income ₹3000",
    "bank transfer received ₹8000",
    "received rent ₹12000",
    "received dividend",
    "received cashback",
    "received refund",
    "commission ₹6000",
    "side income ₹7000",
  ],
  update_budget: [
    "set my monthly budget to ₹20000",
    "update my grocery budget to ₹5000",
    "create a dining budget",
    "increase my shopping budget",
    "set budget",
    "change budget",
    "modify budget",
    "increase budget",
    "decrease budget",
    "edit budget",
    "create monthly budget",
    "set grocery budget",
    "set shopping budget",
    "set dining budget",
    "set travel budget",
    "set entertainment budget",
    "make my budget ₹30000",
    "monthly budget ₹25000",
    "budget should be ₹20000",
    "allocate ₹5000 for groceries",
    "allocate ₹3000 for fuel",
    "allocate ₹4000 for food",
    "increase grocery budget by ₹1000",
    "reduce shopping budget to ₹2000"
  ],

  out_of_scope: [
    "transfer ₹5000 to my friend",
    "pay my electricity bill",
    "invest ₹10000 in stocks",
    "check my bank account balance",
    "show my credit card transactions",
    "open a new bank account",
    "apply for a loan",
    "send money through upi",
    "buy cryptocurrency",
    "access my bank statements",
    "transfer money",
    "pay rent automatically",
    "pay credit card bill",
    "book a flight",
    "book movie tickets",
    "order groceries",
    "buy gold",
    "buy mutual funds",
    "trade stocks",
    "check bank balance",
    "connect my bank account",
    "withdraw money",
    "deposit money",
    "send money",
    "make a payment",
    "pay using upi",
    "pay using credit card",
    "block my debit card",
    "reset my atm pin",
    "generate bank statement",
    "open fixed deposit",
    "close my bank account",
    "apply for insurance",
    "pay my taxes",
    "file income tax",
    "apply for a credit card",
    "show my cibil score",
    "check loan eligibility",
    "buy bitcoin",
    "sell cryptocurrency"
  ],

  greeting: [
    "hello",
    "hi",
    "hey",
    "greetings",
    "good morning",
    "how are you",
    "good afternoon",
    "good evening",
    "good night",
    "hi there",
    "hello there",
    "hey there",
    "hiya",
    "yo",
    "what's up",
    "nice to meet you",
    "how's it going",
    "how are things",
    "welcome",
    "good day",
    "morning",
    "afternoon",
    "evening",
    "hello sage",
    "hi sage",
    "hey sage"
  ]
};
